### ISSUE TITLE
Cannot start the app

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/sudokular#8] opened 2019-07-11 17:54 UTC
There is a critical GLib error on startup. You have to fix this:

```bash
$ com.github.bartzaalberg.sudokular 

(process:26841): GLib-GIO-ERROR **: 19:51:51.277: Settings schema 'com.github.bartzaalberg.sudokular' is not installed

Trappe pour point d'arrêt et de trace
```

**Comment by unbelievableflavour** [comment] 2019-07-12 14:28
Ouch. Fixing

**Comment by unbelievableflavour** [comment] 2019-07-12 23:18
You already closed it. Did the problem resolve by itself? @NathanBnm I couldn't reproduce the issue btw.

**Comment by NathanBnm** [comment] 2019-07-13 05:48
Sorry I didn't want to close this, I have to check first.
Did you add the `com.github.bartzaalberg.sudokular.gschemas.xml` file which is missing?
I think that you should implement it to add a rule about dark theme support, and rules about window size and position.

**Comment by ryonakano** [comment] 2019-07-13 07:42
This is because GSettings Schema Setting isn't compiled after installation in the current code. We need to execute post installation script like [this](https://github.com/ryonakano/reco/blob/master/meson/post_install.py) and run `glib-compile-schemas` to compile the newly installed GSettings Schema.

**Comment by NathanBnm** [comment] 2019-07-13 14:38
Thanks for your remark, I was going to check but now we just have to fix this!

**Comment by unbelievableflavour** [comment] 2019-07-15 09:35
Ok, but that's already in the readme. So it's not really an issue. Like the MR though!

**Comment by ryonakano** [comment] 2019-07-15 09:47
Yes, it's on the readme, but I thought it would be even better to execute that command automatically after the installation as elementary apps/projects or many of other elementary third-party apps does so that developers who frequently contribute to these projects can build the app as they expected.

**Comment by NathanBnm** [comment] 2019-07-15 09:53
I agree with @ryonakano

**Closed as completed** 2019-07-15 14:58 UTC

**Comment by unbelievableflavour** [comment] 2019-07-15 15:02
I agree, but the issue was that the app could not run. Which was already solved. But it doesn't really matter because the PR has been merged!
