### ISSUE TITLE
Better Welcome Screen

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/sudokular#7] opened 2019-07-06 14:05 UTC
I think you should improve the Welcome Screen:

![image](https://user-images.githubusercontent.com/45366162/60757186-86e6d200-a007-11e9-8089-dee31f80d9fd.png)

You should use something like this:

![image](https://user-images.githubusercontent.com/45366162/60757201-a7169100-a007-11e9-967c-2f6771f59c4f.png)

You can add the option to start a new game or to load the previous game (you can disable the option if there is none) instead of using an infobar. Using a red infobar lets the user think that it is an error.

**Comment by unbelievableflavour** [comment] 2019-07-10 12:55
I wanted to add the welcome screen. But the problem is that I can't use images so I would have to custom create that screen or don't use the image at all. What do you  think?

**Comment by unbelievableflavour** [comment] 2019-07-10 19:16
Already done!, Looks a bit better now. Might add some icons later.

**Comment by unbelievableflavour** [comment] 2019-07-12 14:28
Closing this. Icons is nog part of the issue

**Closed as completed by unbelievableflavour** 2019-07-12 14:28 UTC
